var bodyParser = require('body-parser');
var urlEncodedParser = bodyParser.urlencoded({extended: "false"});
var validUrl = require('valid-url');
var path = require('path');
var dir = path.join(__dirname, '../views/index.html');

module.exports = function(app, dbUrl){
    app.get('/', function(req, res){
        res.sendFile(dir);
    });
    app.get('/api/:url*', function(req, res){
        var url = req.url;
        url = url.slice(5);
        if(validUrl.isWebUri(url)){
            var generated = false;
            // while(!generated){
                var rgn = Math.trunc((Math.random() * 10000));
                if(rgn < 1000){
                    rgn+=1000;
                }
                dbUrl.find({num:rgn}, function(err, data){
                    if(err){
                        throw err;
                    }
                    if(data.length > 0){ // number exists
                        console.log("Number generated by rgn exists already ... finding another");
                    }
                    else{
                        generated = true;
                        console.log("Great! Your number is: " + rgn);
                        dbUrl({num: rgn, url: url}).save(function(err, data){
                            if(err){
                                throw err;
                            }
                            else{
                                res.json(data);
                                console.log("Saved!");
                            }
                        });
                    }
                });
            // } 
        }   
        else{
            console.log("URL is invalid!");
        }
    });

    // Check if valid shortened url and redirect (valid means 4 chars long and 0-9 numbers only)
    app.get('/url/:nums', function(req, res){
        var nums = req.params.nums;
        if((nums.length == 4) && !isNaN(nums) && (nums.indexOf('e') == -1)){
            dbUrl.find({num:nums}, function(err, data){
                if(err){
                    throw err;
                }
                if(data.length > 0){
                    res.redirect(data[0]["url"]);
                }
                else{
                    console.log("Does not exist in database!");
                }
            });
        }
        else{
            console.log("Invalid short url!");
        }
    });
}